using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SimManagerLRTA : SimulationManager
{
    //FORMAMOS UN LABERINTO EN LA ESCENA, EL SIMULATION MANAGER RECOGE LAS POSICIONES DEL LABERINTO, EL STEERING LRTA ACCEDE A ESAS POSICIONES Y BUSCA LOCALMENTE (CERCA DE LA POSICION DEL PERSONAJE, CON CIERTO RANGO)
    //EL ALGORITMO LRTA ES SENCILLO, PUEDE IR BIEN
}
